-- BarterThat backend schema. Paste this whole file into Supabase → SQL Editor → Run.
-- Safe to run more than once. Row Level Security locks every table so people can
-- only change their own data, while the marketplace stays publicly readable.

-- ── PROFILES ────────────────────────────────────────────────────────────────
create table if not exists public.profiles (
  id uuid primary key references auth.users on delete cascade,
  data jsonb not null default '{}',
  updated_at timestamptz default now()
);
alter table public.profiles enable row level security;
drop policy if exists profiles_read on public.profiles;
create policy profiles_read on public.profiles for select using (true);
drop policy if exists profiles_insert on public.profiles;
create policy profiles_insert on public.profiles for insert with check (auth.uid() = id);
drop policy if exists profiles_update on public.profiles;
create policy profiles_update on public.profiles for update using (auth.uid() = id);

-- ── LISTINGS (shared marketplace — everyone sees them) ───────────────────────
create table if not exists public.listings (
  id bigint generated by default as identity primary key,
  uid uuid not null references auth.users on delete cascade,
  cat text,
  type text,
  data jsonb not null default '{}',
  created_at timestamptz default now()
);
alter table public.listings enable row level security;
drop policy if exists listings_read on public.listings;
create policy listings_read on public.listings for select using (true);
drop policy if exists listings_insert on public.listings;
create policy listings_insert on public.listings for insert with check (auth.uid() = uid);
drop policy if exists listings_update on public.listings;
create policy listings_update on public.listings for update using (auth.uid() = uid);
drop policy if exists listings_delete on public.listings;
create policy listings_delete on public.listings for delete using (auth.uid() = uid);
create index if not exists listings_cat_idx on public.listings (cat);
create index if not exists listings_uid_idx on public.listings (uid);

-- ── TRADES (between two participants) ────────────────────────────────────────
create table if not exists public.trades (
  id bigint generated by default as identity primary key,
  participants uuid[] not null,
  data jsonb not null default '{}',
  status text default 'pending',
  created_at timestamptz default now()
);
alter table public.trades enable row level security;
drop policy if exists trades_select on public.trades;
create policy trades_select on public.trades for select using (auth.uid() = any(participants));
drop policy if exists trades_insert on public.trades;
create policy trades_insert on public.trades for insert with check (auth.uid() = any(participants));
drop policy if exists trades_update on public.trades;
create policy trades_update on public.trades for update using (auth.uid() = any(participants));

-- ── MESSAGES (chat inside a trade) ───────────────────────────────────────────
create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  trade_id bigint references public.trades on delete cascade,
  from_uid uuid not null references auth.users,
  data jsonb not null default '{}',  -- { text, lang, translations:{ es:"...", fr:"..." } }
  created_at timestamptz default now()
);
alter table public.messages enable row level security;
drop policy if exists messages_select on public.messages;
create policy messages_select on public.messages for select using (
  exists (select 1 from public.trades t where t.id = trade_id and auth.uid() = any(t.participants))
);
drop policy if exists messages_insert on public.messages;
create policy messages_insert on public.messages for insert with check (
  auth.uid() = from_uid and exists (select 1 from public.trades t where t.id = trade_id and auth.uid() = any(t.participants))
);

-- ── BACKINGS (crowdfunding: token pledges + investor-interest pledges) ───────
create table if not exists public.backings (
  id bigint generated by default as identity primary key,
  listing_id bigint references public.listings on delete cascade,
  backer_uid uuid references auth.users,
  kind text,                 -- 'tokens' | 'interest'
  amount numeric default 0,
  data jsonb default '{}',
  created_at timestamptz default now()
);
alter table public.backings enable row level security;
drop policy if exists backings_read on public.backings;
create policy backings_read on public.backings for select using (true);
drop policy if exists backings_insert on public.backings;
create policy backings_insert on public.backings for insert with check (auth.uid() = backer_uid);

-- ── REALTIME (live updates for chat + marketplace) ───────────────────────────
do $$ begin
  alter publication supabase_realtime add table public.messages;
exception when others then null; end $$;
do $$ begin
  alter publication supabase_realtime add table public.listings;
exception when others then null; end $$;
do $$ begin
  alter publication supabase_realtime add table public.trades;
exception when others then null; end $$;
