// BarterThat — Master Category & Service System
// 1000+ services across 30 categories

export const CATS = [
  {
    id: "beauty",
    label: "Beauty & Personal Care",
    icon: "✦",
    both: true,
    subs: [
      "Hair braiding — knotless","Hair braiding — box braids","Hair braiding — cornrows",
      "Hair braiding — senegalese twists","Hair braiding — passion twists",
      "Hair braiding — butterfly locs","Hair braiding — faux locs",
      "Hair braiding — boho braids","Natural hair styling","Silk press",
      "Blowout","Wash & go","TWA styling","Bantu knots","Flat twist styles",
      "Loc installation","Loc retwist","Loc repair","Loc extensions",
      "Sisterlocks installation","Sisterlocks maintenance","Hair coloring & highlights",
      "Balayage","Ombre coloring","Natural hair coloring","Keratin treatment",
      "Hair relaxer","Hair extensions — sew-in","Hair extensions — tape-in",
      "Hair extensions — clip-in","Hair extensions — fusion","Wig install",
      "Wig customization","Wig ventilation","Wig making — lace front",
      "Wig making — full lace","Wig making — closure","Wig styling",
      "Wig repair","Frontal install","Closure install",
      "Lash extensions — classic","Lash extensions — hybrid","Lash extensions — volume",
      "Lash extensions — mega volume","Lash lift","Lash tint","Lash removal",
      "Nail art — acrylic full set","Nail art — acrylic fill","Nail art — gel manicure",
      "Nail art — dip powder","Nail art — polygel","Nail art — press-on application",
      "Nail art — nail designs & decals","Nail art — chrome powder nails",
      "Pedicure — classic","Pedicure — spa","Pedicure — gel polish",
      "Nail repair","Eyebrow microblading","Eyebrow threading",
      "Eyebrow waxing","Eyebrow lamination","Eyebrow tinting",
      "Esthetician — classic facial","Esthetician — deep cleansing facial",
      "Esthetician — hydrating facial","Esthetician — acne facial",
      "Esthetician — brightening facial","Microneedling","Dermaplaning",
      "Chemical peel — light","Chemical peel — medium","Microdermabrasion",
      "LED light therapy","High frequency facial","Radiofrequency skin tightening",
      "Lip blush tattoo","Permanent eyeliner","Permanent eyebrows",
      "Areola restoration tattoo","Scar camouflage tattoo",
      "Spray tan — full body","Spray tan — express","Body waxing — full body",
      "Body waxing — bikini","Body waxing — Brazilian","Body waxing — legs",
      "Body waxing — arms","Body waxing — back","Sugaring hair removal",
      "Laser hair removal consulting","Makeup — everyday glam",
      "Makeup — special occasion","Makeup — bridal","Makeup — editorial",
      "Makeup — theatrical","Sfx makeup","Airbrush makeup",
      "Barber — fade & lineup","Barber — skin fade","Barber — taper",
      "Barber — shave & hot towel","Barber — beard sculpting",
      "Barber — kids haircut","Barber — hair design",
      "Body contouring — wood therapy","Body contouring — cavitation",
      "Body contouring — cupping","Ear candling","Eyelash perms",
      "Teeth whitening — at home kit","Teeth whitening — LED session",
      "Ear piercing","Body piercing","Nose piercing consulting",
      "Hair steaming","Protein treatment","Scalp treatment","Scalp massage",
    ]
  },
  {
    id: "wellness",
    label: "Wellness & Healing",
    icon: "◎",
    both: true,
    subs: [
      "Yoga — hatha","Yoga — vinyasa","Yoga — yin","Yoga — restorative",
      "Yoga — kundalini","Yoga — hot yoga","Yoga — prenatal","Yoga — kids",
      "Yoga — chair yoga for seniors","Pilates — mat","Pilates — reformer",
      "Pilates — prenatal","Breathwork — pranayama","Breathwork — holotropic",
      "Breathwork — transformational","Meditation — guided","Meditation — transcendental",
      "Meditation — mindfulness","Meditation — body scan","Sound bath healing",
      "Tibetan singing bowls","Gong bath","Crystal bowl healing",
      "Reiki — level 1","Reiki — level 2","Reiki — distance healing",
      "Acupuncture — pain management","Acupuncture — fertility",
      "Acupuncture — stress & anxiety","Acupuncture — weight management",
      "Cupping therapy","Gua sha facial","Gua sha body",
      "Aromatherapy session","Essential oil consulting",
      "Crystal healing session","Chakra balancing","Aura reading",
      "Tarot reading","Oracle card reading","Astrology reading",
      "Human design reading","Numerology reading","Palm reading",
      "Herbalism consulting","Herbal remedy creation","Herbal tea blending",
      "Ayurvedic consulting","Ayurvedic meal planning","Dosha assessment",
      "Life coaching — career","Life coaching — relationships",
      "Life coaching — mindset","Life coaching — spiritual",
      "Somatic therapy coaching","Trauma-informed coaching",
      "Grief support coaching","Divorce coaching",
      "Addiction recovery coaching","Weight loss coaching",
      "Body image coaching","Anxiety management coaching",
      "IV hydration therapy","Vitamin injection consulting",
      "Chiropractic care","Spinal adjustment","Sports chiropractic",
      "Physical therapy","Sports rehabilitation","Manual therapy",
      "Occupational therapy","Speech therapy","Nutritional coaching",
      "Macros & meal plan creation","Intuitive eating coaching",
      "Plant-based nutrition coaching","Sports nutrition coaching",
      "Hypnotherapy","EFT tapping","EMDR coaching support",
      "Cold plunge hosting","Sauna session hosting",
      "Float tank session","Infrared sauna session",
      "Mental health coaching","Mindset coaching",
      "Sleep coaching","Hormone health consulting",
      "Fertility wellness coaching","Postpartum wellness coaching",
      "Menopause support coaching","Men's health coaching",
    ]
  },
  {
    id: "fitness",
    label: "Fitness & Sports Training",
    icon: "⊕",
    both: true,
    subs: [
      "Personal training — weight loss","Personal training — muscle building",
      "Personal training — functional fitness","Personal training — senior fitness",
      "Personal training — youth fitness","Personal training — prenatal",
      "Personal training — postpartum","Group fitness class instruction",
      "CrossFit coaching","HIIT training","Circuit training",
      "Strength & conditioning","Olympic weightlifting coaching",
      "Powerlifting coaching","Bodybuilding coaching","Calisthenics coaching",
      "Boxing coaching","Kickboxing instruction","Muay Thai instruction",
      "MMA coaching","Brazilian jiu-jitsu","Wrestling coaching",
      "Judo instruction","Karate instruction","Taekwondo instruction",
      "Krav maga instruction","Self-defense — women's",
      "Self-defense — children's","Self-defense — senior",
      "Swim coaching — beginner","Swim coaching — competitive",
      "Swim lessons — toddlers","Swim lessons — adults",
      "Dance — hip hop","Dance — ballet","Dance — jazz",
      "Dance — contemporary","Dance — salsa","Dance — bachata",
      "Dance — ballroom","Dance — tap","Dance — pole fitness",
      "Dance — afrobeats","Dance — belly dancing",
      "Gymnastics coaching","Cheer coaching","Tumbling instruction",
      "Yoga teacher training support","Pilates instructor training support",
      "Running coaching — 5k","Running coaching — marathon",
      "Cycling coaching","Triathlon coaching","Obstacle race coaching",
      "Golf instruction","Tennis instruction","Pickleball coaching",
      "Basketball skills coaching","Football skills coaching",
      "Soccer skills coaching","Baseball skills coaching",
      "Volleyball coaching","Track & field coaching",
      "Rock climbing coaching","Skateboarding coaching",
      "Surfing lessons","Snowboard coaching","Ski instruction",
      "Horseback riding instruction","Equestrian coaching",
      "Sports performance coaching","Athletic speed & agility training",
      "Youth sports development","Sports nutrition for athletes",
      "Injury prevention coaching","Flexibility & mobility coaching",
      "CPR certification training","First aid certification training",
      "BLS certification training","AED training",
    ]
  },
  {
    id: "food",
    label: "Food & Culinary Arts",
    icon: "◉",
    both: false,
    subs: [
      "Meal prep — weekly","Meal prep — family","Meal prep — macro-focused",
      "Meal prep — vegan","Meal prep — keto","Meal prep — gluten-free",
      "Meal prep — diabetic-friendly","Meal prep — heart-healthy",
      "Personal chef — dinner party","Personal chef — weekly cooking",
      "Personal chef — special occasion","Cooking lessons — beginner",
      "Cooking lessons — intermediate","Cooking lessons — cultural cuisine",
      "Cooking lessons — baking","Cooking lessons — pastry",
      "Sourdough bread — loaves","Sourdough starter kits",
      "Artisan bread — focaccia","Artisan bread — baguette",
      "Custom cakes — birthday","Custom cakes — wedding",
      "Custom cakes — celebration","Cupcakes — custom decorated",
      "Cookies — custom decorated","Cookies — sugar","Cookies — chocolate chip",
      "Macarons","Cheesecakes","Pies & tarts","Brownies & bars",
      "Pastries — croissants","Pastries — danishes",
      "Donuts — custom","Cinnamon rolls","Banana bread & quick breads",
      "Muffins","Pound cake","Carrot cake","Red velvet cake",
      "Tres leches","Churros","Conchas & pan dulce",
      "Jamaican patties","Caribbean food","Soul food platters",
      "Southern BBQ — brisket","Southern BBQ — ribs","Southern BBQ — pulled pork",
      "Smoked meats — custom","Food by the pound — beef",
      "Food by the pound — chicken","Food by the pound — lamb",
      "Food by the pound — seafood","Food by the pound — pork",
      "Catering — small events","Catering — large events",
      "Catering — corporate lunches","Catering — weddings",
      "Meal kits — weekly","Charcuterie boards — personal",
      "Charcuterie boards — large grazing","Hot sauce — custom blends",
      "Salsa & condiments","Fermented foods — kimchi",
      "Fermented foods — sauerkraut","Fermented foods — pickles",
      "Kombucha brewing","Kefir making","Jams & jellies",
      "Fruit preserves","Honey products","Flavored salts & spice blends",
      "Vegan cheese making","Butter & ghee making",
      "Cocktail catering","Mocktail catering","Bartending services",
      "Specialty coffee roasting","Tea blending",
      "Private dinner experience","Pop-up dining experience",
      "Food truck catering","Ghost kitchen consulting",
      "Recipe development","Food styling for photos",
      "Dietary consulting — allergy-friendly",
      "Meal planning — weight loss","Meal planning — muscle gain",
    ]
  },
  {
    id: "farming",
    label: "Farming & Homestead",
    icon: "❧",
    both: false,
    subs: [
      "Farm fresh eggs — dozen","Farm fresh eggs — bulk",
      "Raw milk — cow","Raw milk — goat",
      "Pasteurized milk","Artisan cheese — soft",
      "Artisan cheese — hard","Goat cheese",
      "Butter making","Cream & cultured dairy",
      "Raw honey — wildflower","Raw honey — clover",
      "Infused honey","Beeswax products","Beeswax candles",
      "Propolis & bee pollen","Fresh herbs — basil",
      "Fresh herbs — mint","Fresh herbs — rosemary",
      "Fresh herbs — thyme","Fresh herb bundles",
      "Dried herbs","Herb seedlings",
      "Seasonal vegetables — box","Seasonal fruit — box",
      "Microgreens — trays","Microgreens — wholesale",
      "Edible flowers","Mushrooms — oyster",
      "Mushrooms — shiitake","Mushrooms — lion's mane",
      "Mushroom grow kits","Foraged goods",
      "Seedlings & starter plants","Heirloom seeds",
      "Bulk grains & legumes","Flour — stone ground",
      "Cornmeal — stone ground","Dried beans & lentils",
      "Backyard chicken setup consulting","Goat care consulting",
      "Rabbit farming","Aquaponics setup",
      "Hydroponics setup","Composting system setup",
      "Worm farm setup","Rainwater collection setup",
      "Canning & food preservation lessons",
      "Fermentation lessons","Beekeeping setup & lessons",
      "Urban farming consulting","Farm-to-table box subscriptions",
      "Livestock care consulting","Poultry care",
      "Homestead design consulting","Off-grid living consulting",
      "Soil testing & amendment","Garden bed soil prep",
      "Raised bed construction","Greenhouse setup",
    ]
  },
  {
    id: "home",
    label: "Home Services & Repair",
    icon: "⌂",
    both: false,
    subs: [
      "General handyman — small jobs","General handyman — half day",
      "General handyman — full day","Interior painting — room",
      "Interior painting — full house","Exterior painting — trim",
      "Exterior painting — full house","Cabinet painting & refinishing",
      "Deck staining & sealing","Fence painting & staining",
      "Drywall repair — patches","Drywall installation",
      "Texture — orange peel","Texture — knockdown",
      "Popcorn ceiling removal","Crown molding installation",
      "Baseboard installation","Flooring — hardwood install",
      "Flooring — laminate install","Flooring — vinyl plank install",
      "Flooring — tile install","Flooring — carpet install",
      "Flooring — epoxy garage","Floor refinishing",
      "Tile work — bathroom","Tile work — kitchen backsplash",
      "Tile work — shower","Tile work — floor",
      "Grout cleaning & sealing","Cabinet installation — kitchen",
      "Cabinet installation — bathroom","Cabinet refacing",
      "Kitchen remodel — full","Kitchen remodel — partial",
      "Bathroom remodel — full","Bathroom remodel — partial",
      "Basement finishing","Attic conversion",
      "Mudroom build","Laundry room build",
      "Home addition consulting","ADU planning",
      "Electrical — outlets & switches","Electrical — ceiling fan install",
      "Electrical — lighting install","Electrical — panel upgrade",
      "Electrical — EV charger install","Electrical — rewiring",
      "Plumbing — leak repair","Plumbing — faucet install",
      "Plumbing — toilet install","Plumbing — water heater",
      "Plumbing — drain cleaning","Plumbing — pipe replacement",
      "HVAC — filter & maintenance","HVAC — installation",
      "HVAC — repair","HVAC — duct cleaning",
      "Roofing — inspection","Roofing — repair",
      "Roofing — full replacement","Roofing — flat roof",
      "Roofing — metal roof","Gutter cleaning",
      "Gutter installation","Gutter guards",
      "Insulation — attic","Insulation — spray foam",
      "Solar panel installation","Solar consulting",
      "Smart home — Nest & thermostat","Smart home — lighting",
      "Smart home — security cameras","Smart home — doorbell",
      "Security system install","TV mounting — standard",
      "TV mounting — fireplace","TV mounting — outdoor",
      "Furniture assembly — flat pack","Furniture assembly — large",
      "Door installation — interior","Door installation — exterior",
      "Window installation","Window repair","Screen repair",
      "Lock install & rekey","Deadbolt installation",
      "Pressure washing — driveway","Pressure washing — house",
      "Pressure washing — deck","Window cleaning — interior",
      "Window cleaning — exterior","Garage door repair",
      "Garage door install","Deck building","Deck repair",
      "Porch building","Pergola build","Fence install — wood",
      "Fence install — vinyl","Fence install — chain link",
      "Concrete — driveway","Concrete — sidewalk",
      "Concrete — patio","Concrete repair","Masonry — brick",
      "Masonry — stone","Foundation crack repair",
      "Waterproofing — basement","Waterproofing — crawl space",
      "Mold remediation","Fire damage restoration",
      "Water damage restoration","Asbestos testing consulting",
      "Lead paint testing consulting","Home inspection consulting",
      "Handyman — furniture rearranging","Handyman — picture hanging",
      "Handyman — caulking & weatherstripping",
    ]
  },
  {
    id: "garden",
    label: "Garden & Outdoor Living",
    icon: "❦",
    both: false,
    subs: [
      "Lawn mowing — small yard","Lawn mowing — large yard",
      "Lawn mowing — weekly service","Lawn fertilizing",
      "Lawn aeration","Overseeding","Sod installation",
      "Mulching","Edging & trimming","Weed control",
      "Landscaping design — front yard","Landscaping design — backyard",
      "Landscaping design — full property","Landscape installation",
      "Tree planting","Tree trimming","Tree removal",
      "Stump grinding","Bush & shrub trimming",
      "Hedge sculpting","Flower bed planting",
      "Perennial garden design","Annual garden maintenance",
      "Native plant garden","Pollinator garden",
      "Rain garden design","Vegetable garden setup",
      "Herb garden build","Container garden design",
      "Irrigation — drip system","Irrigation — sprinkler install",
      "Irrigation — repair","Outdoor lighting — pathway",
      "Outdoor lighting — string lights","Outdoor lighting — landscape",
      "Snow removal — residential","Snow removal — commercial",
      "De-icing & salting","Leaf removal — fall cleanup",
      "Spring yard cleanup","Fall yard cleanup",
      "Pest control — lawn","Pest control — garden",
      "Outdoor kitchen build","Fire pit installation",
      "Pergola build","Gazebo assembly","Patio furniture assembly",
      "Artificial turf install","Garden pond design",
      "Water feature installation","Retaining wall build",
      "Raised garden bed build","Greenhouse assembly",
      "Compost bin setup","Rain barrel install",
      "Seasonal planting service","Plant propagation",
      "Plant sitting & care","Indoor plant consulting",
    ]
  },
  {
    id: "construction",
    label: "Construction & Building",
    icon: "◫",
    both: false,
    subs: [
      "New construction consulting","ADU — design consulting",
      "ADU — permits consulting","ADU — build project management",
      "Tiny home build consulting","Tiny home design",
      "Shed build — small","Shed build — large",
      "Pole barn construction","Steel building erection",
      "Barndominium build consulting","Container home build consulting",
      "Architectural drafting — residential","Architectural drafting — commercial",
      "Blueprint reading & review","Structural consulting",
      "Permit filing assistance","Permit consulting",
      "Construction project management","General contracting consulting",
      "Subcontractor sourcing","Land clearing","Grading & leveling",
      "Excavation","Septic system install","Well drilling consulting",
      "Foundation — pour","Foundation — pier & beam",
      "Retaining wall — concrete","Retaining wall — stone",
      "Retaining wall — timber","Driveway paving — asphalt",
      "Driveway paving — concrete","Driveway repair",
      "Parking lot striping","Sidewalk pour",
      "Framing — wood","Framing — steel",
      "Roofing — new construction","Siding install — vinyl",
      "Siding install — hardie board","Siding install — wood",
      "Insulation — new construction","Building wrapping",
      "3D printing — construction parts","3D printing — architecture models",
      "Laser cutting — architectural","CNC — custom millwork",
      "Custom stair build","Custom railing install",
      "Skylight installation","Solar tube install",
      "Pool construction consulting","Pool decking",
      "Hot tub installation","Sauna build",
      "Home theater build","Man cave build",
      "She shed build","Playhouse build","Treehouse build",
    ]
  },
  {
    id: "creative",
    label: "Creative Arts & Design",
    icon: "◈",
    both: true,
    subs: [
      "Graphic design — logo","Graphic design — brand identity",
      "Graphic design — flyers","Graphic design — business cards",
      "Graphic design — menus","Graphic design — merch",
      "Graphic design — packaging","Graphic design — social media templates",
      "Graphic design — infographics","Graphic design — book covers",
      "Graphic design — album covers","Graphic design — signage",
      "Photography — portraits","Photography — family",
      "Photography — newborn","Photography — maternity",
      "Photography — graduation","Photography — headshots",
      "Photography — boudoir","Photography — events",
      "Photography — weddings","Photography — commercial",
      "Photography — real estate","Photography — product",
      "Photography — food","Photography — fashion",
      "Photography — sports","Photography — aerial drone",
      "Photography — underwater","Videography — weddings",
      "Videography — events","Videography — music videos",
      "Videography — real estate tours","Videography — social media content",
      "Videography — brand films","Videography — documentaries",
      "Video editing — YouTube","Video editing — TikTok",
      "Video editing — reels","Video editing — commercials",
      "Video editing — wedding films","Motion graphics",
      "Animation — 2D","Animation — 3D",
      "Animation — character design","Podcast production",
      "Podcast editing","Podcast cover art",
      "Music production — beats","Music production — full track",
      "Music production — mixing","Music production — mastering",
      "Jingle & commercial music","Sound design",
      "Voiceover — commercials","Voiceover — audiobooks",
      "Voiceover — explainer videos","Voiceover — character voices",
      "Illustration — digital","Illustration — hand-drawn",
      "Illustration — children's book","Illustration — comic",
      "Illustration — tattoo design","Tattoo artistry — blackwork",
      "Tattoo artistry — fine line","Tattoo artistry — traditional",
      "Tattoo artistry — realism","Tattoo artistry — watercolor",
      "Tattoo artistry — geometric","Tattoo artistry — cover-up",
      "Tattoo — touch up","Tattoo consulting & design",
      "Mural painting — indoor","Mural painting — outdoor",
      "Canvas painting — portraits","Canvas painting — abstract",
      "Watercolor art","Oil painting","Acrylic painting",
      "Portrait commission","Pet portrait","Caricatures",
      "Calligraphy — wedding","Calligraphy — event signage",
      "Hand lettering","Chalkboard art",
      "Custom clothing design","Fashion sketching",
      "Pattern making","Sewing — alterations",
      "Sewing — custom garments","Sewing — costumes",
      "Embroidery — custom","Embroidery — monogramming",
      "Crochet — clothing","Crochet — accessories","Crochet — home décor",
      "Knitting — custom pieces","Quilting — custom",
      "Candle making — custom scents","Candle making — soy",
      "Soap making — cold process","Soap making — hot process",
      "Jewelry making — custom","Jewelry making — beaded",
      "Jewelry making — metalsmithing","Jewelry repair",
      "Pottery — wheel thrown","Pottery — hand built",
      "Ceramics — custom orders","Woodworking — custom furniture",
      "Woodworking — shelving","Woodworking — home décor",
      "Wood burning — pyrography","Custom signs — wood",
      "Custom signs — acrylic","Leatherwork — wallets",
      "Leatherwork — bags","Leatherwork — belts",
      "Stained glass art","Mosaic art","Resin art",
      "Macramé — wall hangings","Macramé — plant hangers",
      "Pressed flower art","Wreath making","Floral arrangement",
    ]
  },
  {
    id: "tech",
    label: "Tech & Digital Services",
    icon: "⬡",
    both: true,
    subs: [
      "Web development — WordPress","Web development — Shopify",
      "Web development — Squarespace","Web development — Wix",
      "Web development — custom React","Web development — Next.js",
      "Web development — Vue.js","Web development — full stack",
      "Web development — landing pages","Web development — e-commerce",
      "Mobile app — iOS","Mobile app — Android",
      "Mobile app — React Native","Mobile app — Flutter",
      "UI/UX design","Product design","Wireframing",
      "Prototype building — Figma","Design system creation",
      "IT support — home","IT support — small business",
      "IT support — network setup","Computer repair — PC",
      "Computer repair — Mac","Virus removal",
      "Data recovery","Hard drive upgrade",
      "RAM upgrade","OS installation",
      "Phone repair — screen","Phone repair — battery",
      "Phone repair — charging port","Tablet repair",
      "Network setup — home WiFi","Network setup — mesh system",
      "Network setup — business","Server setup",
      "Cybersecurity consulting","VPN setup",
      "Password manager setup","Security audit — small business",
      "SEO — on-page","SEO — technical","SEO — local",
      "SEO — e-commerce","SEO audit",
      "Google Ads management","Meta Ads management",
      "TikTok Ads management","Pinterest Ads",
      "Email marketing — setup","Email marketing — campaigns",
      "Email marketing — automation","Klaviyo setup",
      "Mailchimp setup","Social media management — Instagram",
      "Social media management — TikTok","Social media management — Facebook",
      "Social media management — LinkedIn","Social media management — Pinterest",
      "Content calendar creation","Hashtag strategy",
      "Data analysis — Excel","Data analysis — Google Sheets",
      "Data analysis — Python","Data analysis — Tableau",
      "Data analysis — Power BI","Dashboard creation",
      "AI chatbot building","AI automation setup",
      "Zapier automation","Make (Integromat) automation",
      "CRM setup — HubSpot","CRM setup — Salesforce",
      "CRM setup — Go High Level","E-commerce setup — Amazon FBA",
      "E-commerce setup — Etsy","E-commerce setup — TikTok Shop",
      "Dropshipping setup","Print-on-demand setup",
      "Database management — MySQL","Database management — PostgreSQL",
      "Cloud setup — AWS","Cloud setup — Google Cloud",
      "Cloud setup — Azure","QuickBooks setup",
      "Software training — Microsoft Office","Software training — Google Workspace",
      "Tech support — seniors","Tech setup — new device",
      "Business digitization","File organization — cloud",
      "3D printing — prototypes","3D printing — custom parts",
      "3D printing — jewelry","3D printing — home décor",
      "3D printing — cosplay props","3D printing — figurines",
      "Laser cutting — wood","Laser cutting — acrylic",
      "Laser cutting — leather","Laser engraving — gifts",
      "CNC routing — signs","CNC routing — furniture parts",
      "Electronics repair","Drone setup & calibration",
      "Smart home — Google Home","Smart home — Amazon Alexa",
      "Smart home — Apple HomeKit","Smart home — full setup",
      "Gaming PC build","Streaming setup — Twitch/YouTube",
      "Podcast tech setup","Home studio tech setup",
    ]
  },
  {
    id: "events",
    label: "Events & Celebrations",
    icon: "◇",
    both: false,
    subs: [
      "Wedding planning — full service","Wedding planning — partial",
      "Wedding planning — day-of coordination","Engagement party planning",
      "Bridal shower planning","Bachelorette party planning",
      "Bachelor party planning","Rehearsal dinner planning",
      "Baby shower planning","Sip & paint event planning",
      "Kids birthday party planning","Teen birthday party planning",
      "Adult birthday party planning","Quinceañera planning",
      "Sweet 16 planning","Debutante ball planning",
      "Graduation party planning","Retirement party planning",
      "Anniversary party planning","Holiday party planning",
      "Corporate event planning","Team building events",
      "Conference planning","Product launch events",
      "Grand opening planning","Charity gala planning",
      "Fundraiser event planning","Pop-up event planning",
      "Block party planning","Cultural celebration planning",
      "Juneteenth event planning","Kwanzaa event planning",
      "Eid celebration planning","Diwali event planning",
      "Florist — wedding florals","Florist — event florals",
      "Florist — everyday arrangements","Florist — sympathy arrangements",
      "Florist — corporate","Balloon decoration — arch",
      "Balloon decoration — column","Balloon decoration — garland",
      "Balloon decoration — centerpieces","Balloon — organic installations",
      "Event decorating & styling","Tablescaping",
      "Event lighting design","Uplighting rental",
      "Photo backdrop rental","Neon sign rental",
      "Marquee letter rental","Photo booth rental",
      "360 photo booth","DJ services — weddings",
      "DJ services — parties","DJ services — corporate",
      "DJ services — school events","Live band booking consulting",
      "Live music — acoustic","Live music — jazz",
      "Live music — R&B","Live music — gospel",
      "MC & hosting services","Spoken word performance",
      "Caricature artist","Face painting",
      "Glitter tattoos","Henna artist",
      "Magician","Juggler","Balloon animals",
      "Comedian — booking consulting","Character entertainer",
      "Tent rental","Table & chair rental",
      "Linen rental","Charger plate rental",
      "Venue scouting","Venue consulting",
      "Catering management","Bartending services",
      "Mocktail bar setup","Hot cocoa bar setup",
      "Dessert table styling","Candy buffet setup",
      "Invitation design","Save the date design",
      "Wedding website design","Seating chart design",
      "Program design","Menu design",
      "Party favor creation","Custom gift bags",
      "Wedding favors","Centerpiece creation",
    ]
  },
  {
    id: "care",
    label: "Care & Support Services",
    icon: "♡",
    both: false,
    subs: [
      "Child care — infant","Child care — toddler",
      "Child care — school age","Child care — after school",
      "Child care — overnight","Child care — weekend",
      "Nanny services — part time","Nanny services — full time",
      "Nanny share coordination","Au pair consulting",
      "Special needs childcare — autism","Special needs childcare — Down syndrome",
      "Special needs childcare — cerebral palsy",
      "Special needs childcare — ADHD support",
      "Homework help — elementary","Homework help — middle school",
      "Homework help — high school","Homework projects assistance",
      "Science fair project help","Reading support",
      "Elder care — companion visits","Elder care — in-home CNA",
      "Elder care — medication reminders","Elder care — meal preparation",
      "Elder care — transportation","Elder care — light housekeeping",
      "Senior companion — social","Senior companion — tech help",
      "Senior companion — errands","Post-surgery in-home care",
      "Respite care for caregivers","Overnight elder care",
      "Memory care companion","Hospice companion support",
      "Disability support — personal care","Disability support — mobility assist",
      "Disability support — communication","Home health aide services",
      "Postpartum doula","Newborn care specialist",
      "Birth doula","Placenta encapsulation",
      "Lactation consulting","Newborn photography",
      "Baby sleep training consulting","Potty training consulting",
      "Neonatal support","NICU family support",
      "Pet sitting — dogs","Pet sitting — cats",
      "Pet sitting — birds","Pet sitting — reptiles",
      "Pet sitting — small animals","Pet boarding — home-based",
      "Dog walking — single","Dog walking — group",
      "Dog running","Dog grooming — bath & brush",
      "Dog grooming — full groom","Dog grooming — breed specific",
      "Cat grooming","Pet nail trim","Pet ear cleaning",
      "Dog training — basic obedience","Dog training — advanced",
      "Dog training — puppy","Dog training — behavior issues",
      "Dog training — service dog support","Exotic pet care",
      "Pet food — homemade dog treats","Pet food — homemade cat treats",
      "Pet food — raw diet prep","Veterinary care consulting",
      "Pet loss grief support","Pet memorial photography",
      "House sitting — with pets","House sitting — without pets",
    ]
  },
  {
    id: "companionship",
    label: "Companionship & Social Wellness",
    icon: "◑",
    both: true,
    subs: [
      "Platonic event escort — weddings","Platonic event escort — galas",
      "Platonic event escort — work events","Platonic event escort — family events",
      "Plus-one for social events","Plus-one for networking events",
      "Friendly companion — dining out","Friendly companion — movies",
      "Friendly companion — concerts","Friendly companion — museums",
      "Friendly companion — travel","Friendly companion — day trips",
      "Senior social companion — outings","Senior social companion — home visits",
      "Senior companion — phone check-ins","Senior companion — tech teaching",
      "Hospital & appointment companion","Medical appointment support",
      "Therapy appointment support","Recovery companion",
      "Virtual friendship — chat support","Virtual check-in companion",
      "Activity partner — hiking","Activity partner — fitness",
      "Activity partner — cooking","Activity partner — crafts",
      "Language exchange partner","Cultural exchange companion",
      "New-to-city orientation guide","Neighborhood welcome tour",
      "Accountability partner — fitness","Accountability partner — business",
      "Accountability partner — sobriety","Accountability partner — study",
      "Grief support companion","Divorce transition companion",
      "New mom support companion","Postpartum social companion",
      "Men's emotional support circle","Women's circle facilitation",
      "Blind date facilitation — platonic networking",
      "Professional networking facilitation",
      "Social anxiety support companion",
      "Autism social skills practice partner",
      "Introvert-friendly social coaching",
    ]
  },
  {
    id: "lessons",
    label: "Lessons, Tutoring & Coaching",
    icon: "◎",
    both: true,
    subs: [
      "Music lessons — guitar (beginner)","Music lessons — guitar (advanced)",
      "Music lessons — piano (beginner)","Music lessons — piano (advanced)",
      "Music lessons — drums","Music lessons — bass guitar",
      "Music lessons — violin","Music lessons — cello",
      "Music lessons — trumpet","Music lessons — saxophone",
      "Music lessons — flute","Music lessons — harp",
      "Music lessons — ukulele","Music lessons — banjo",
      "Singing lessons — beginner","Singing lessons — advanced",
      "Choir coaching","Music theory","Ear training",
      "Songwriting coaching","Beat making lessons",
      "Music production lessons","DJ lessons",
      "Language tutoring — Spanish","Language tutoring — French",
      "Language tutoring — Mandarin","Language tutoring — Arabic",
      "Language tutoring — Portuguese","Language tutoring — Japanese",
      "Language tutoring — Korean","Language tutoring — Swahili",
      "Language tutoring — Haitian Creole","Language tutoring — ASL",
      "Academic tutoring — elementary math","Academic tutoring — algebra",
      "Academic tutoring — geometry","Academic tutoring — calculus",
      "Academic tutoring — statistics","Academic tutoring — biology",
      "Academic tutoring — chemistry","Academic tutoring — physics",
      "Academic tutoring — English","Academic tutoring — writing",
      "Academic tutoring — history","Academic tutoring — economics",
      "SAT prep","ACT prep","GRE prep","GMAT prep",
      "LSAT prep","MCAT prep","College essay coaching",
      "College application consulting","Scholarship essay coaching",
      "Homeschool curriculum consulting","Special education tutoring",
      "Dyslexia support tutoring","ADHD study coaching",
      "ESL — English as second language","ESL — business English",
      "Coding — Python for beginners","Coding — JavaScript",
      "Coding — Java","Coding — SQL","Coding — web development",
      "Coding — kids programming","Chess coaching",
      "Poker strategy coaching","Art lessons — drawing",
      "Art lessons — painting","Art lessons — digital art",
      "Photography lessons","Video editing lessons",
      "Cooking lessons — world cuisine","Baking lessons",
      "Gardening lessons","Sewing lessons",
      "Knitting & crochet lessons","Calligraphy lessons",
      "Pottery lessons","Woodworking lessons",
      "Acting coaching","Film acting coaching",
      "Public speaking coaching","Debate coaching",
      "Presentation skills coaching","Interview prep coaching",
      "Business coaching — startup","Business coaching — scaling",
      "Business coaching — marketing","Business coaching — operations",
      "Entrepreneurship mentoring","Side hustle coaching",
      "Social media strategy coaching","Content creation coaching",
      "Financial literacy coaching","Budgeting coaching",
      "Debt management coaching","Credit repair coaching",
      "Investment basics coaching","Real estate investing coaching",
      "Crypto & blockchain basics coaching",
      "Driving lessons — beginner","Driving lessons — highway",
      "Driving lessons — parallel parking","Motorcycle safety training",
      "Horseback riding lessons","Sailing lessons","Kayaking lessons",
      "Surfing lessons","Rock climbing lessons",
      "Wilderness survival training","Navigation & orienteering",
      "Self-defense — women","Self-defense — children",
      "CPR & first aid instruction","CERT training support",
      "Test anxiety coaching","Study skills coaching",
      "Time management coaching","Organization coaching",
    ]
  },
  {
    id: "auto",
    label: "Auto, Vehicles & Transportation",
    icon: "⊕",
    both: false,
    subs: [
      "Car detailing — exterior wash & wax","Car detailing — interior deep clean",
      "Car detailing — full detail","Car detailing — ceramic coating",
      "Car detailing — paint correction","Car detailing — engine bay",
      "Car detailing — headlight restoration","Car detailing — odor removal",
      "Auto maintenance — oil change","Auto maintenance — tire rotation",
      "Auto maintenance — brake inspection","Auto maintenance — brake service",
      "Auto maintenance — battery replacement","Auto maintenance — air filter",
      "Auto maintenance — fluid check & top-off","Auto maintenance — tune-up",
      "Mobile mechanic — diagnostics","Mobile mechanic — alternator",
      "Mobile mechanic — starter","Mobile mechanic — belts & hoses",
      "Mobile mechanic — suspension","Mobile mechanic — AC recharge",
      "Auto body — dent repair","Auto body — scratch repair",
      "Auto body — fender repair","Auto body — bumper repair",
      "Windshield repair","Windshield replacement",
      "Window tinting","Vehicle wrap install",
      "Car audio install — stereo","Car audio install — speakers",
      "Car audio install — subwoofer","Car audio install — backup camera",
      "Car audio install — remote start","Dash cam install",
      "Vehicle inspection — pre-purchase","Vehicle inspection — safety",
      "Car buying consulting","Car flipping consulting",
      "Classic car restoration consulting","Lowrider build consulting",
      "RV maintenance","RV inspection","Boat detailing",
      "Boat maintenance","Jet ski maintenance",
      "Motorcycle repair","Motorcycle detailing",
      "ATV repair","Golf cart repair",
      "E-bike repair","Bicycle repair","Bicycle tune-up",
      "Parking spot rental — daily","Parking spot rental — monthly",
      "Airport shuttle","Moving truck driving",
      "Rideshare setup consulting","Vehicle transport",
      "Car trading & swapping","Truck trading",
      "Motorcycle trading","Vintage car trading",
      "RV trading","Boat trading","ATV trading",
      "E-bike trading","Equipment trading",
    ]
  },
  {
    id: "professional",
    label: "Professional & Business Services",
    icon: "◻",
    both: true,
    subs: [
      "Accounting — personal bookkeeping","Accounting — business bookkeeping",
      "Accounting — QuickBooks setup","Accounting — catch-up bookkeeping",
      "Accounting — financial statements","Accounting — cash flow management",
      "Tax preparation — personal (1040)","Tax preparation — self-employed",
      "Tax preparation — small business","Tax preparation — LLC",
      "Tax preparation — S-Corp","Tax preparation — nonprofit",
      "Tax planning consulting","Back taxes consulting",
      "IRS audit support consulting","Financial planning — budgeting",
      "Financial planning — retirement","Financial planning — college savings",
      "Business plan writing","Pitch deck creation",
      "Investor memo writing","Executive summary writing",
      "Grant writing — nonprofit","Grant writing — small business",
      "SBIR/STTR grant consulting","SBA loan consulting",
      "Legal consulting — contracts","Legal consulting — business formation",
      "Legal consulting — intellectual property","Legal consulting — real estate",
      "Legal consulting — family law","Legal consulting — immigration",
      "Legal consulting — criminal (licensed)","Contract drafting",
      "Contract review","NDA drafting","Terms of service writing",
      "Trademark filing assistance","Copyright registration",
      "LLC formation consulting","S-Corp election consulting",
      "Nonprofit 501c3 consulting","Business license consulting",
      "Notary services","Apostille consulting",
      "HR consulting — hiring","HR consulting — policies",
      "HR consulting — employee relations","HR consulting — compliance",
      "Recruitment & headhunting","Resume screening",
      "Payroll setup — Gusto","Payroll setup — ADP",
      "Payroll processing","Employee handbook writing",
      "Operations consulting","Process improvement consulting",
      "Business credit building","Personal credit repair consulting",
      "Insurance consulting — business","Insurance consulting — health",
      "Insurance consulting — life","Insurance consulting — auto",
      "Real estate consulting — buying","Real estate consulting — selling",
      "Real estate consulting — investing","Real estate consulting — commercial",
      "Short-term rental consulting","Property management consulting",
      "Franchise consulting","Import/export consulting",
      "Supply chain consulting","Vendor sourcing",
      "Business exit strategy consulting","Mergers & acquisitions consulting",
      "Marketing strategy consulting","Brand strategy consulting",
      "PR strategy consulting","Influencer strategy",
      "Nonprofit management consulting","Board development consulting",
      "IRTA barter exchange compliance","1099-B barter tax reporting",
    ]
  },
  {
    id: "medical",
    label: "Health & Medical Services",
    icon: "✚",
    both: true,
    subs: [
      "Dental — cleaning & exam","Dental — X-rays","Dental — whitening",
      "Dental — fillings consulting","Dental — crown consulting",
      "Dental — extraction consulting","Dental — implant consulting",
      "Dental — orthodontics consulting","Dental — Invisalign consulting",
      "Dental — veneers consulting","Dental — emergency consulting",
      "Vision — eye exam","Vision — glasses consulting",
      "Vision — contact lens fitting","Vision — LASIK consulting",
      "Medical — general health consulting","Medical — telehealth visit",
      "Medical — second opinion consulting","Lab result interpretation",
      "Medical billing consulting","Health insurance navigation",
      "Medical records organization","Medicare consulting",
      "Medicaid consulting","Healthcare proxy setup consulting",
      "Advance directive consulting","Living will consulting",
      "Home nursing visit","Wound care","IV infusion at home",
      "Injection administration","Medication management consulting",
      "Phlebotomy — blood draw","Phlebotomy — wellness panels",
      "Hearing aid consulting","Audiologist consulting",
      "Physical therapy — knee","Physical therapy — back",
      "Physical therapy — shoulder","Physical therapy — hip",
      "Physical therapy — sports injury","Physical therapy — post-surgery",
      "Occupational therapy — hand","Occupational therapy — pediatric",
      "Occupational therapy — cognitive","Speech therapy — articulation",
      "Speech therapy — stuttering","Speech therapy — language delay",
      "Speech therapy — swallowing","Audiology — hearing test",
      "Chiropractic — back pain","Chiropractic — neck pain",
      "Chiropractic — sports","Chiropractic — prenatal",
      "Doula — birth","Doula — postpartum","Doula — bereavement",
      "Lactation consulting","Breastfeeding support",
      "Newborn care specialist","Baby sleep training consulting",
      "Pediatric health consulting","Teen health consulting",
      "Men's health consulting","Women's health consulting",
      "Fertility consulting","Reproductive health consulting",
      "Mental health therapy (licensed)","Counseling — couples",
      "Counseling — family","Counseling — grief",
      "Counseling — trauma","Counseling — addiction",
      "CPR training","BLS training","ACLS support training",
      "First aid training","AED training",
      "Medical coding consulting","HIPAA consulting",
      "Telehealth platform setup","Medical practice consulting",
    ]
  },
  {
    id: "certifications",
    label: "Certifications & Professional Training",
    icon: "▣",
    both: true,
    subs: [
      "CPR certification — adult","CPR certification — pediatric",
      "CPR certification — infant","BLS certification",
      "ACLS certification support","PALS certification support",
      "First aid certification","AED certification",
      "OSHA 10 training","OSHA 30 training",
      "Forklift certification training","Aerial lift certification",
      "Confined space entry training","Hazmat training",
      "Fire safety training","Food handler certification",
      "ServSafe certification prep","Alcohol service certification (TIPS)",
      "Cosmetology board exam prep","Esthetics board exam prep",
      "Nail tech board exam prep","Barber board exam prep",
      "Real estate license exam prep","Real estate broker exam prep",
      "Mortgage loan originator prep","Home inspector certification prep",
      "General contractor license prep","Electrician license prep",
      "Plumbing license prep","HVAC certification prep",
      "Notary certification training","Apostille certification consulting",
      "Security guard training","Private investigator consulting",
      "Bail bondsman consulting","Insurance license exam prep",
      "Series 6 & 7 exam prep","CFP exam prep",
      "CPA exam prep","EA (enrolled agent) exam prep",
      "Project management (PMP) prep","Agile & Scrum certification prep",
      "Six Sigma white belt","Six Sigma yellow belt",
      "Six Sigma green belt prep","Lean management training",
      "Google Analytics certification prep","HubSpot certification prep",
      "Facebook Blueprint prep","Google Ads certification prep",
      "AWS cloud certification prep","Google Cloud certification prep",
      "Microsoft Azure certification prep","CompTIA A+ prep",
      "CompTIA Security+ prep","Cisco CCNA prep",
      "Coding bootcamp tutoring","Data science certification prep",
      "Personal trainer — NASM prep","Personal trainer — ACE prep",
      "Personal trainer — ISSA prep","Group fitness instructor prep",
      "Yoga teacher training (200hr)","Yoga teacher training (300hr)",
      "Pilates instructor certification prep","Nutrition coach certification prep",
      "Health coach certification prep","Life coach certification prep",
      "CNA certification training","HHA certification training",
      "Phlebotomy certification training","Medical assistant prep",
      "Medical coding certification prep","Medical billing prep",
      "EMT certification prep","Paramedic training support",
      "Pharmacy technician prep","Dental assistant prep",
      "Vet tech certification prep","Animal care certification",
      "Bookkeeping certification — QuickBooks","Bookkeeping certification — Xero",
      "Paralegal certification prep","Court reporting prep",
      "CDL truck driving training","Hazmat endorsement prep",
      "Drone pilot — FAA Part 107 prep","Ham radio licensing prep",
      "FCC license prep","Commercial fishing license consulting",
      "Hunting & fishing license consulting","Firearms safety certification",
      "Concealed carry permit prep","Range safety officer training",
      "Childcare certification prep","Early childhood education prep",
      "Teacher certification (Praxis) prep","Special education certification prep",
    ]
  },
  {
    id: "travel",
    label: "Travel, Stays & Experiences",
    icon: "✈",
    both: true,
    subs: [
      "Flight deal brokering","Business class upgrade consulting",
      "First class deal consulting","Flight points & miles consulting",
      "Travel hacking — credit card strategy","Airline companion pass consulting",
      "Hotel deal brokering","Boutique hotel consulting",
      "All-inclusive resort consulting","Hotel points consulting",
      "Vacation package planning","Caribbean trip planning",
      "Mexico vacation planning","European trip planning",
      "African heritage trip planning","Asia trip planning",
      "South America trip planning","Road trip planning",
      "RV trip planning","Cruise deal brokering",
      "Cruise excursion planning","Timeshare swap consulting",
      "VRBO & Airbnb deal consulting","House swap consulting",
      "House sitting — short term","House sitting — long term",
      "Pet-friendly house sitting","Property check-in services",
      "Airbnb co-hosting","Vacation rental management",
      "Short-term rental setup","Airbnb photography",
      "Airbnb listing optimization","Airbnb interior styling",
      "Local city tour — walking","Local city tour — food",
      "Local city tour — history","Local city tour — art",
      "Local city tour — nightlife","Cultural immersion experience",
      "Local hidden gems guide","Black-owned business tour guide",
      "Travel photography","Destination wedding planning",
      "Honeymoon planning","Babymoon planning",
      "Bachelorette trip planning","Bachelor trip planning",
      "Group travel coordination","Family reunion trip planning",
      "Girls trip planning","Guys trip planning",
      "Solo travel safety consulting","Digital nomad setup consulting",
      "Visa & passport consulting","Global Entry consulting",
      "TSA PreCheck consulting","NEXUS card consulting",
      "Travel insurance consulting","International driving permit consulting",
      "Packing consulting","Luxury travel consulting",
      "Budget travel consulting","Accessible travel consulting",
      "Senior travel consulting","Student travel planning",
    ]
  },
  {
    id: "collectibles",
    label: "Collectibles, Valuables & Big Trades",
    icon: "◈",
    both: true,
    subs: [
      "Autographed — sports jersey","Autographed — sports ball",
      "Autographed — sports card","Autographed — sports photo",
      "Autographed — music memorabilia","Autographed — movie memorabilia",
      "Autographed — book signed by author","Autographed — TV memorabilia",
      "Trading cards — sports (graded)","Trading cards — sports (raw)",
      "Trading cards — Pokémon","Trading cards — Magic the Gathering",
      "Trading cards — Yu-Gi-Oh","Trading cards — one piece",
      "Trading cards — basketball","Trading cards — football",
      "Trading cards — baseball","Trading cards — soccer",
      "Vintage clothing — 90s","Vintage clothing — 80s",
      "Vintage clothing — 70s","Vintage clothing — designer",
      "Streetwear — Supreme","Streetwear — Off-White",
      "Streetwear — Bape","Streetwear — vintage Nike",
      "Sneakers — Jordan retros","Sneakers — Nike SB",
      "Sneakers — Yeezy","Sneakers — New Balance",
      "Sneakers — Adidas rare","Sneaker authentication consulting",
      "Luxury watches — Rolex consulting","Luxury watches — AP consulting",
      "Luxury watches — Omega consulting","Watch authentication consulting",
      "Fine jewelry — diamond","Fine jewelry — gold",
      "Fine jewelry — vintage","Jewelry authentication",
      "Fine art — original paintings","Fine art — prints",
      "Fine art — sculpture","Art authentication consulting",
      "Rare vinyl records","First pressing records",
      "First edition books","Rare manuscripts",
      "Comic books — graded","Comic books — raw key issues",
      "Action figures — vintage","Funko Pop — rare",
      "Video games — vintage cartridges","Video games — sealed",
      "Video game consoles — vintage","Coins — graded (PCGS/NGC)",
      "Coins — silver","Coins — gold","Coin collection consulting",
      "Stamps — rare","Currency — foreign vintage",
      "Military memorabilia","Historical artifacts consulting",
      "Movie props & memorabilia","TV show props",
      "Musical instruments — vintage guitar","Musical instruments — violin",
      "Musical instruments — horn","Musical instruments — piano",
      "Sports equipment — vintage","Sports trophies & awards",
      "Priceless family heirlooms (sentimental trade)",
      "Rare whiskey & spirits","Fine wine collection",
      "Luxury handbag — Birkin consulting","Luxury handbag — Chanel consulting",
      "Luxury handbag authentication","Antique furniture",
      "Antique décor","Estate sale items","Auction item consulting",
    ]
  },
  {
    id: "org",
    label: "Organization & Lifestyle Management",
    icon: "▦",
    both: false,
    subs: [
      "Home organizing — kitchen","Home organizing — living room",
      "Home organizing — bedroom","Home organizing — closet",
      "Home organizing — garage","Home organizing — attic",
      "Home organizing — basement","KonMari organizing",
      "Feng shui consulting","Clutter clearing",
      "Minimalism coaching","Estate organizing",
      "Senior move management","Downsizing consulting",
      "Move coordination","Packing service",
      "Unpacking & setup service","Junk removal",
      "Donation coordination","eBay selling setup",
      "Facebook Marketplace consulting","Estate sale management",
      "Digital organizing — files","Digital organizing — photos",
      "Digital organizing — email","Digital organizing — cloud storage",
      "Digital organizing — desktop","Business document organization",
      "Paper filing system setup","Scanning & digitizing documents",
      "Password & account organization","Calendar & schedule organization",
      "Task management system setup","Project management setup",
      "Notion setup & training","Asana setup","Monday.com setup",
      "Laundry service — wash & fold","Laundry service — delicates",
      "Dry cleaning pickup & delivery","Ironing & pressing service",
      "Garment storage consulting","Uniform management",
      "Personal shopping — groceries","Personal shopping — clothing",
      "Personal shopping — gifts","Personal shopping — home décor",
      "Wardrobe audit & edit","Capsule wardrobe building",
      "Seasonal wardrobe switch","Style consulting",
      "Grocery pickup & delivery","Costco run service",
      "Errand running — general","Errand running — medical",
      "Errand running — post office","Meal planning service",
      "Appointment scheduling service","Bill pay assistance for seniors",
      "DMV appointment & errand","Government paperwork assistance",
    ]
  },
  {
    id: "making",
    label: "Making, Fabrication & Printing",
    icon: "◉",
    both: false,
    subs: [
      "3D printing — functional parts","3D printing — custom figurines",
      "3D printing — jewelry","3D printing — home décor",
      "3D printing — cosplay props","3D printing — prototypes",
      "3D printing — medical models","3D printing — architectural models",
      "3D printing — replacement parts","3D printing — custom gifts",
      "3D printing — toys & games","3D modeling design",
      "Laser cutting — wood signs","Laser cutting — acrylic",
      "Laser cutting — leather","Laser cutting — custom shapes",
      "Laser engraving — wood","Laser engraving — metal",
      "Laser engraving — glass","Laser engraving — gifts",
      "CNC routing — furniture parts","CNC routing — custom signs",
      "CNC routing — decorative panels","CNC machining — metal",
      "Welding — MIG","Welding — TIG","Welding — stick",
      "Welding — custom fabrication","Welding — art sculptures",
      "Metal fabrication — railings","Metal fabrication — gates",
      "Metal fabrication — custom furniture","Blacksmithing",
      "Screen printing — t-shirts","Screen printing — hoodies",
      "Screen printing — hats","Heat press — DTF transfers",
      "Heat press — sublimation","Heat press — vinyl decals",
      "Embroidery — custom hats","Embroidery — shirts",
      "Embroidery — bags","Embroidery — patches",
      "Custom merchandise — full setup","Vinyl cutting — decals",
      "Vinyl cutting — vehicle graphics","Vinyl cutting — wall art",
      "Custom signage — yard signs","Custom signage — banners",
      "Custom signage — A-frames","Custom trophies & awards",
      "Custom plaques","Custom coins & medals",
      "Photo printing — canvas","Photo printing — metal",
      "Photo printing — framed prints","Photo book creation",
      "Custom mugs","Custom phone cases","Custom tote bags",
      "Custom pillows","Custom blankets","Custom puzzles",
      "Button & pin making","Custom stickers",
      "Shoe customizing","Sneaker restoration",
      "Leather goods — wallets","Leather goods — belts",
      "Leather goods — custom bags","Upholstery — car seats",
      "Upholstery — furniture","Upholstery — headboards",
      "Furniture restoration","Chalk paint furniture",
      "Furniture flipping","Antique restoration",
      "Custom candles — poured","Custom candles — soy",
      "Custom soap — cold process","Custom soap — glycerin",
      "Bath bombs","Custom perfume blending",
      "Body butter & lotion making","Lip gloss & balm making",
      "Prototype building","Product development consulting",
      "Invention consulting","Patent research consulting",
      "Electronics assembly","Circuit board repair","Soldering services",
    ]
  },
  {
    id: "media",
    label: "Media, Entertainment & Content",
    icon: "◉",
    both: true,
    subs: [
      "Acting coaching — film","Acting coaching — TV",
      "Acting coaching — stage","Acting coaching — commercial",
      "Improv training","Stand-up comedy coaching",
      "Screenwriting coaching","Scriptwriting","Playwriting",
      "Storyboarding","Film directing consulting",
      "Film producing consulting","Casting consulting",
      "Film editing","Color grading",
      "Visual effects consulting","Music video concept creation",
      "Music video direction","Music video production",
      "Album creation consulting","EP recording consulting",
      "Album artwork design","Artist bio writing",
      "Press kit creation","EPK (electronic press kit)",
      "Artist management consulting","Booking agent consulting",
      "Tour management consulting","Concert production consulting",
      "Event promotion","Social media promotion",
      "Playlist pitching consulting","Music sync licensing consulting",
      "Beat licensing consulting","Publishing consulting",
      "Podcast launch — concept","Podcast launch — branding",
      "Podcast launch — technical setup","Podcast editing",
      "Podcast show notes writing","Podcast transcript writing",
      "Podcast pitch to networks","YouTube channel strategy",
      "YouTube thumbnail design","YouTube SEO",
      "YouTube video scripting","YouTube channel management",
      "TikTok strategy","TikTok content creation",
      "Instagram Reels strategy","Instagram growth consulting",
      "Influencer brand deal negotiating","Sponsorship consulting",
      "Content creator tax consulting","Creator LLC setup consulting",
      "Book writing coaching","Book editing",
      "Book cover design","Self-publishing consulting",
      "ISBN & copyright registration","Amazon KDP setup",
      "Audiobook production","Audiobook narration",
      "Ghostwriting — books","Ghostwriting — speeches",
      "Ghostwriting — articles","Ghostwriting — social media",
      "PR & press release writing","Media pitch writing",
      "Crisis communications","Brand reputation consulting",
      "Radio show consulting","Twitch streaming setup",
      "Streaming overlay design","Discord server setup",
      "Game streaming coaching","Esports coaching",
      "Video game tournament organizing",
    ]
  },
  {
    id: "virtual",
    label: "Virtual & Remote Services",
    icon: "⬡",
    both: true,
    subs: [
      "Virtual assistant — general admin","Virtual assistant — executive",
      "Virtual assistant — real estate","Virtual assistant — medical",
      "Virtual assistant — e-commerce","Virtual assistant — social media",
      "Remote receptionist","Online research","Data entry",
      "Data scraping & collection","Web research",
      "Lead generation","CRM data entry","Spreadsheet management",
      "Transcription — audio","Transcription — video",
      "Transcription — medical","Transcription — legal",
      "Closed captioning","Subtitles — foreign language",
      "Translation — Spanish","Translation — French",
      "Translation — Portuguese","Translation — Mandarin",
      "Translation — Arabic","Translation — Haitian Creole",
      "Translation — Swahili","Translation — Japanese",
      "Proofreading — general","Proofreading — academic",
      "Proofreading — business","Copy editing",
      "Developmental editing","Line editing",
      "Blog writing","SEO article writing",
      "Product description writing","Amazon listing copywriting",
      "Email sequence writing","Sales page copywriting",
      "Landing page copywriting","Ad copywriting",
      "Social media caption writing","Newsletter writing",
      "Press release writing","Grant writing — virtual",
      "Speech writing","Wedding vow writing",
      "Eulogy writing","Cover letter writing",
      "Resume writing — entry level","Resume writing — professional",
      "Resume writing — executive","LinkedIn profile optimization",
      "Online course creation — content","Online course creation — tech setup",
      "E-book writing","E-book formatting",
      "E-book cover design","Kindle publishing setup",
      "Online tutoring — K-12","Online tutoring — college",
      "Online tutoring — adult learning","Remote therapy (licensed)",
      "Online life coaching","Virtual fitness coaching",
      "Remote nutritionist","Virtual bookkeeping",
      "Remote tax preparation","Online legal consulting",
      "Remote IT support","Remote customer service",
      "Chat support management","Phone support management",
      "Email management","Calendar management",
      "Travel booking assistance","Project coordination",
      "Online community management","Forum moderation",
      "Podcast virtual assistance","YouTube virtual assistance",
      "Influencer outreach","Brand collaboration outreach",
      "Virtual event coordination","Webinar setup & management",
      "Zoom meeting facilitation","Online survey creation",
      "Market research","Competitor analysis",
      "SWOT analysis","Business report writing",
    ]
  },
  {
    id: "community",
    label: "Community Squads & Circles",
    icon: "⚇",
    both: false,
    subs: [
      "Women's home repair rotation squad","Men's home maintenance crew",
      "Neighborhood gutter cleaning crew","Community yard work rotation",
      "Friends moving squad","Emergency repair brigade",
      "Senior help squad — general tasks","Senior help squad — yard work",
      "Senior help squad — tech support","Senior help squad — grocery runs",
      "Single moms support squad","Single dads support squad",
      "New neighbor welcome crew","Community childcare circle",
    ],
  },
];

// ── BONUS CATEGORIES pushing past 1000 ──────────────────────────

export const EXTRA_CATS = [
  {
    id: "legal_docs",
    label: "Legal Documents & Forms",
    icon: "◻",
    both: true,
    subs: [
      "Will & testament drafting consulting","Living trust consulting",
      "Power of attorney setup","Healthcare proxy setup",
      "Child custody agreement consulting","Divorce document prep consulting",
      "Prenuptial agreement consulting","Postnuptial agreement consulting",
      "Adoption consulting","Name change document consulting",
      "Landlord-tenant lease drafting","Eviction notice consulting",
      "Small claims court prep","Demand letter writing",
      "Cease & desist letter","Non-compete agreement review",
      "Partnership agreement drafting","Operating agreement drafting",
      "Buy-sell agreement consulting","Franchise disclosure consulting",
      "Immigration form prep consulting","DACA renewal consulting",
      "Asylum application consulting","Green card consulting",
      "Citizenship application consulting","Work visa consulting",
      "Student visa consulting","Travel document consulting",
    ]
  },
  {
    id: "real_estate",
    label: "Real Estate Services",
    icon: "⌂",
    both: true,
    subs: [
      "Home buying consulting","Home selling consulting",
      "First-time homebuyer coaching","Down payment assistance consulting",
      "Home inspection prep","Appraisal consulting",
      "Mortgage pre-approval coaching","Mortgage rate consulting",
      "Refinancing consulting","HELOC consulting",
      "Investment property analysis","Rental property setup",
      "Property management consulting","Tenant screening consulting",
      "Lease drafting consulting","Eviction process consulting",
      "Short-term rental — Airbnb setup","STR regulations consulting",
      "House hacking consulting","BRRRR method coaching",
      "Fix & flip consulting","Wholesale real estate consulting",
      "Land investing consulting","Commercial real estate intro consulting",
      "Real estate syndication basics","REITs consulting",
      "1031 exchange consulting","Opportunity zone consulting",
      "Real estate LLC setup consulting","Landlord insurance consulting",
      "Home staging consulting","Home staging — full",
      "Real estate photography","Virtual staging",
      "Real estate video tour","Open house coordination",
      "MLS listing consulting","For Sale By Owner support",
      "HOA dispute consulting","Condo association consulting",
    ]
  },
  {
    id: "finance_personal",
    label: "Personal Finance & Money Management",
    icon: "◎",
    both: true,
    subs: [
      "Budget creation & coaching","Zero-based budgeting coaching",
      "Envelope system setup","Debt snowball coaching",
      "Debt avalanche coaching","Student loan consulting",
      "Student loan forgiveness consulting","Credit card debt payoff coaching",
      "Medical debt negotiation consulting","Collections consulting",
      "Credit score improvement coaching","Credit report review",
      "Credit repair consulting","Building credit from scratch",
      "Business credit building","DUNS number setup consulting",
      "Business credit card strategy","Net 30 vendor account setup",
      "Savings goal coaching","Emergency fund coaching",
      "High yield savings consulting","CD & money market consulting",
      "401k optimization consulting","Roth IRA setup consulting",
      "Traditional IRA consulting","SEP IRA consulting",
      "HSA setup & strategy","FSA strategy consulting",
      "Social Security benefits consulting","Medicare enrollment consulting",
      "Life insurance needs consulting","Term vs whole life consulting",
      "Disability insurance consulting","Identity theft recovery consulting",
      "FAFSA financial aid consulting","Scholarship money management",
      "Teen money management coaching","Kids & allowance coaching",
      "Financial independence coaching","FIRE movement coaching",
      "Frugal living coaching","Minimalist finance coaching",
    ]
  },
];

export const ALL_CATS = [...CATS, ...EXTRA_CATS];
export const GRAND_TOTAL = ALL_CATS.reduce((a, c) => a + c.subs.length, 0);
